pipeline {
    agent any

    environment {
        IMAGE_NAME = "mazenelsayad/bloggingapp"
        IMAGE_TAG = "v${BUILD_NUMBER}"
        REGISTRY = "docker.io"
    }

    stages {

        stage("Checkout") {
            steps {
                checkout scm
                sh 'echo "Branch: $(git rev-parse --abbrev-ref HEAD)"'
            }
        }

        stage("Build Maven") {
            steps {
                dir('fullstack-blogging-app') { // انتقل لمجلد المشروع
                    sh "./mvnw clean package -DskipTests"
                }
            }
            post {
                always {
                    archiveArtifacts artifacts: 'fullstack-blogging-app/target/*.jar', allowEmptyArchive: true
                }
            }
        }

        stage("Build Docker Image") {
            steps {
                dir('fullstack-blogging-app') {
                    withCredentials([usernamePassword(
                        credentialsId: 'DOCKERHUB_CREDENTIALS',
                        usernameVariable: 'USER',
                        passwordVariable: 'PASS'
                    )]) {
                        sh """
                            echo "$PASS" | docker login -u "$USER" --password-stdin
                            docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
                            docker push ${IMAGE_NAME}:${IMAGE_TAG}
                        """
                    }
                }
            }
        }

        stage("Update Kubernetes Manifest") {
            steps {
                dir('fullstack-blogging-app/k8s') {
                    sh """
                    sed -i "s|image: .*|image: ${IMAGE_NAME}:${IMAGE_TAG}|g" application.yaml
                    cat application.yaml | grep image -n
                    """
                }
            }
        }

        stage("Deploy to Kubernetes") {
            steps {
                withCredentials([string(credentialsId: 'K8S_CONFIG', variable: 'KUBECONFIG_CONTENT')]) {
                    sh '''
                        # احفظ محتوى Secret Text مؤقتًا في ملف
                        echo "$KUBECONFIG_CONTENT" > kubeconfig_temp
                        export KUBECONFIG=$(pwd)/kubeconfig_temp

                        # نطبّق ملفات YAML على cluster
                        kubectl apply -f fullstack-blogging-app/k8s/namespace.yaml
                        kubectl apply -f fullstack-blogging-app/k8s/
                    '''
                }
            }
        }
    }

    post {
        success {
            echo "Deployment completed successfully!"
        }
        failure {
            echo "Pipeline failed."
        }
    }
}
